### ISSUE TITLE
AM_EXTRA_RECURSIVE_TARGETS makes the bootstrap fail in some machines

### ISSUE THREAD

**Issue by coppolachan** [paboyle/Grid#101]
Clearly we need an environment that is updated enough.
AM_EXTRA_RECURSIVE_TARGETS is failing at the HPCS in Cambridge where previous versions of Grid were compiling without problems.
The version of autoconf there is 2.63 and automake 1.11.1
Either we try to avoid this make target or we force some newer version of the automake tools that currently is only requiring 2.63.
It is a pity though that we loose support for several machines only because of this m4 script.

**Comment by paboyle** [comment]
We could install newer automake. I did this on BlueGene.
Can you ask Cambridge support?

**Comment by aportelli** [comment]
I did not have time to answer this weekend before the release, but if one dive into the git history, I actually started my implementation of the `test` target using `AM_EXTRA_RECURSIVE_TARGETS`. I have been then rolling back because of incompatibilities of the kind Guido mentioned that were important enough such that I had to implement the recursive thing myself. I do not remember which target was problematic, but my guess is Travis or the BG/Q.

My opinion is that the computers we connect to should have an up to date autotool setup, this macro is rather old. This might be idealistic though, in which case we can still go back to the previous implementation.

**Comment by paboyle** [comment]
Hi Antonin,

I agreed with your point of view, and thought that we have the option of manually installing auto tools
everywhere *except* Travis. The version is not recent, and Ubuntu Trusty includes it. That was how
I got the Travis running.

The Make system is massively simplified by this,  I felt it not too burdensome as a tradeoff.

But, we can discuss. Best is to get global installs in /usr/local/ second best is for users to individually update.

Peter

**Comment by coppolachan** [comment]
Sure, actually I realised that there are modules for the newer versions in the HPCS. 
I was raising the point in order to establish a policy.
I agree on this in principle
"Best is to get global installs in /usr/local/ second best is for users to individually update."

If we are going into this path then we should update the minimal autotools version supported in the configure.ac

**Comment by paboyle** [comment]
Completely agree. I am going to have to take action on v0.7.0 anyway and we can update this at the same time.

**Comment by paboyle** [comment]
Closing. I made the configure check.
