### ISSUE TITLE
Travis compilation/testing taking too long with clang

### ISSUE THREAD

**Issue by coppolachan** [paboyle/Grid#107]
We are hitting the time walls for the compilation and testing with clang.
Currently develop is marked errored because it cannot complete one of the clang compilation/tests in time.

We should drop some tests in this case.

**Comment by paboyle** [comment]
yes. Antonin is really close with our own CI server and for now this creates
throw away work. Can Antonin comment with the ETA on the CI ?

**Comment by aportelli** [comment]
Probably during next week for AVX2 & AVX512 using Cori & my KNL to sharpen the scripts. Then things will evolve from there with generic, local AVX on a VM, ARM & QPX. 

I would not care too much about Travis at this point.

We will probably lose the macOS target, setting a macOS VM is a non-trivial thing without commercial VM solutions because the VM needs to be good enough so that the OS believes it's a Mac.

**Comment by paboyle** [comment]
Cliath is nearly working but not going clean due to the JSON issue. 

Suggest we update JSON from the Lohmann website since they claim a fix was committed 13 days ago, make Cliath go CI clean, the SWITCH OFF Travis altogether and rely on Cliath/TeamCity CI only.

We will need to set links between Cliath and Github somehow, so "clean/unclean" is visible from Github?

**Comment by aportelli** [comment]
> Cliath is nearly working but not going clean due to the JSON issue.
>
> Suggest we update JSON from the Lohmann website since they claim a fix was committed 13 days  ago, make Cliath go CI clean, the SWITCH OFF Travis altogether and rely on Cliath/TeamCity CI > only.

Agreed

> We will need to set links between Cliath and Github somehow, so "clean/unclean" is visible from Github?

This is the case since a while, if you put your cursor on any red/green mark you will see the Cliath report, if you look at an open pull request you will see that TeamCity is part of the request validation.

I have also prepared new badges for the readme that show the TeamCity status, it is in a branch I am waiting the final go to merge it into `develop`.

**Comment by aportelli** [comment]
And like I said in another thread I'll look at the JSON update/fix.

**Comment by paboyle** [comment]
Thanks for picking up the JSON Antonin,

I think you will need to show me the cursor thing. Better done verbally on the corridor and not through issues databases ! I've been used to looking in the "README.md" for build status,
but from what you say there must be somewhere else or some other method I'm unaware of.

Peter

**Comment by coppolachan** [comment]
Closing since the JSON is fixed (modulo a small modification if the teamcity agents to load a version of gcc>=4.9)
