### ISSUE TITLE
Fragile while() loop in lib/communicator/SharedMemoryMPI.cc

### ISSUE THREAD

**Issue by kkissell** [paboyle/Grid#149]
Line 141 of lib/communicator/SharedMemoryMPI.cc is:

while ( (WorldDims[dim] / ShmDims[dim]) <= 1 ) dim=(dim+1)%ndimension;

However, if Benchmark_ITT is run with --mpi 1.1.1.1 or --mpi 2.1.1.1, the inequality will always be true and the while loop is infinite.  Those may be bad options to specify, but hanging forever with no diagostic is probably neither optimal nor necessary.  I'm a little unclear as to the intent of the code, so I hesitate to propose a specific fix.

**Comment by paboyle** [comment]
Curious...

It's easy to replace with safe for loop of length ndimension, but
have you actually hit the problem or this by inspection ?

I was able to run on my laptop with --mpi 1.1.1.1 and --mpi 2.1.1.1 just fine, and instrumented 
a print statement on this while loop.

It should never enter a case where there not free nodes (i.e. WorldDims > ShmDims for
some dimension, otherwise there is a logic error, which should have been trapped by earlier
asserts unless I missed something).

e.g. when --mpi 2.1.1.1 on one node (2 ranks per node)
initially 

  log2size = 1;  l2 = 0 , ShmDims = { 1,1,1,1 }, WorldDims = { 2,1,1,1 }

  The while terminates with Dim = 0;

  ShmDims <-   {2,1,1,1}

  l2 <- 1

More generally, 2^{log2size} nodes are present, and we require that the product
of dimensions be == number ranks.

We always have l2 < log2size in this loop, and there must always be
at least one dimension for which WorldDims[d] > ShmDims[d] in each iteration of this loop,
and that dim is found by the while loop with periodic advance on "d".

For 1.1.1.1 the loop is never entered, since log2size is 0, and the
for loop on l2 terminates with zero iterations.

Have I missed something ?

**Comment by kkissell** [comment]
I came across the loop empirically, attaching to a hung process with gdb.  The program was almost certainly in an abnormal state - I've been working on issues that seem to be related to shared memory provisioning, where despite having the recommended number of pages provisioned, initialization was failing, so I experimentally reduced the dimensions of the --mpi argument, and stumbled on the infinite loop.

**Comment by paboyle** [comment]
OK -- I'll instrument the loop. I think it should never be hit when called with sensible
state, but indeed better for such code to "scream and commit suicide" than fall into a coma.

Let you know when the commit is in.

Peter

**Comment by paboyle** [comment]
This code was rewritten
