### ISSUE TITLE
Consider std::array in place of boost::array

### ISSUE THREAD

**Issue by mspraggs** [paboyle/Grid#2]
You mention boost arrays in the TODO list, so I thought I'd mention this on the off-chance you hadn't already seen it. C++11 provides an array class template that's pretty much the same as the boost array type.

**Comment by paboyle** [comment]
Isn't the array template fixed size one dimensional [compile time templated]?

Might work for Nd type indices, but not generally usable; secondly the boost array has really nice
multi-dimensional features and subslicing extents. So it would merge multi1d,2d,3d to Nd neatly
and give subslicing. Just annoyed it hasn't made it into a standard and don't like dependency on boost.

Another thought is that in general I'm getting quite annoyed that vector resize loops
over dimension calling default constructor, giving slow resize. Will benchmark this again,
but for a while I tried (incorrectly) to call reserve and prevent the loop.

If I remember right, it is an implementation issue: the loop is implemented by 
i) calling the default constructor once on a temporary if not is_pod.
ii) looping over the whole array using the copy constructor for each element
    passing it the temporary.
iii) in the case where the default constructor does nothing, is_pod still says not plain old
data, the empty constructor does nothing to the temporary, but then it loops over the whole
volume copying the temporary that contains junk.

This is avoidable with an "is_pod" enable_if in valarray (and possibly vector haven't checked); but
std::complex is forcing it to still use the slow resize were I to use valarray because it triggers and "is_pod" failure.

So, at some point I may be forced to roll my own "simple" array container that suppresses
initialisation of arrays to junk in resize and initial allocate when is_pod==false.

Question is then whether I make it a multi-dim like boost arrays, or fix to vector like 1d.

**Comment by paboyle** [comment]
This is the sort of offending loop, that creates a default object and issues a loop
of length the allocation EVEN if the default contstructor is trival and thus filling with random junk.
The implementation should be guarded with enable_if<has_trivial_constructor<value_type> > to
avoid the loop when the constructor is empty.
     
 void
      resize(size_type __new_size, value_type __x = value_type())
      {
	if (__new_size < size())
	  _M_erase_at_end(this->_M_impl._M_start + __new_size);
	else
	  insert(end(), __new_size - size(), __x);
      }

**Comment by paboyle** [comment]
sorry for brain dumping Matt -- origin of misunderstanding -- my comments in the 
TODO were intended to mean Boost's MultiArray:

http://www.boost.org/doc/libs/1_58_0/libs/multi_array/doc/

which is a very interesting interface.

**Comment by mspraggs** [comment]
Ah sure, I see what you mean. Yeah std::array won't help for multi-dimensional arrays.
