### ISSUE TITLE
Primes need to be enlarged

### ISSUE THREAD

**Issue by joelgiedt** [paboyle/Grid#297]
Hi, I'm running on a system that has shared memory cores involving the primes 2 and 7.  So I had to add 7 to the array of primes in communicator/SharedMemoryMPI.cc in the function GetShmDims,  This solved an error I was getting.

**Comment by paboyle** [comment]
I can add 7, but bear in mind Grid is intended to be used with one MPI rank per socket, and thread OpenMP within a socket.
I'm surprised the 7 is not in the OMP_NUM_THREAD

**Comment by joelgiedt** [comment]
OK, I'll use --threads to deal with the factor of 7 instead.

**Comment by paboyle** [comment]
It's not just to "deal with the factor of 7" -- it's FASTER to use threads within a NUMA domain.

If you communicate within a socket using MPI, you must gather a face (RW) transfer data RW and then Read to use, so that's 5 crossings of the CPU-Memory interface. 

It's clearly faster to just read the data instead -- when the memory access is uniform which it is within a socket.
