### ISSUE TITLE
Single node (no GPU) performance question

### ISSUE THREAD

**Issue by plvlnisse** [paboyle/Grid#324]
The performance reported for the benchmark run on a single AMD Rome node without GPUs is intriguing. Can you share details about the configure command line and the command line used to run this?

**Comment by paboyle** [comment]
Thanks. 
This was specifically on Benchmark_dwf on 16x16x16x64 volume; a KMP_AFFINITY flag was needed. 

We no longer have access to that node, it was for a Hackathon, and cannot run the frozen Benchmark_ITT.

Benchmark_ITT benchmarks the same loop as Benchmark_dwf, but the volumes are swept, and swept differently.

It is likely that the comparison points 24^4 and 32^4 fall out of cache on Rome, but we cannot run to check. 
I wouldn't be surprised if there is a big cache edge, see slides at:

https://github.com/paboyle/Grid/wiki/Benchmark_ITT:-Example-output#rome-results-from-july-2020-dirac-amd-hackathon

You can see a big drop on a synthetic intra-node comms benchmark on slide 2, as a cache edge effect. 
But I'm not able to measure where this happens on Benchmark_dwf or Benchmark_ITT due to access.

**Comment by paboyle** [comment]
Benchmark_dwf_fp32 .. sorry. 

The code back then (July) still had --enable-precision=single

**Comment by paboyle** [comment]
closing
