### ISSUE TITLE
AVXFMA4?

### ISSUE THREAD

**Issue by aportelli** [paboyle/Grid#47]
Hi,

My laptop does not support AVX2 instructions. When I try to compile with `AVXFMA4`, the compilation craches complaining that I am using AVX2 intrinsics unsupported by my machine.
So my question is: is that really an AVX1+FMA target or did it become redundant with AVX2 (especially now that Peter added `-mfma` to `AVX2`)?

**Comment by paboyle** [comment]
be careful -- AVXFMA4 is the AMD opteron version for BlueWaters which has one set of multiply add instructions (four operand). 

These are sadly incompatible with AVX2 FMA instructions (three operand).

**Comment by aportelli** [comment]
Ok thanks for the explanation I certainly did not understand that.

**Comment by paboyle** [comment]
There's some interesting history.
AMD and Intel published new instructions to try to converge on common ground.
AMD decided to implement Intel's
Intel decided to implement AMD's
The chance of converging was lost.

**Comment by paboyle** [comment]
https://en.wikipedia.org/wiki/FMA_instruction_set

The incompatibility between Intel's FMA3 and AMD's FMA4 is due to both companies changing plans without coordinating coding details with each other. AMD changed their plans from FMA3 to FMA4 while Intel changed their plans from FMA4 to FMA3 almost at the same time. The history can be summarized as follows:

August 2007: AMD announces the SSE5 instruction set, which includes 3-operand FMA instructions. A new coding scheme (DREX) is introduced for allowing instructions to have three operands.[6]
April 2008: Intel announces their AVX and FMA instruction sets, including 4-operand FMA instructions. The coding of these instructions uses the new VEX coding scheme which is more flexible than AMD's DREX scheme. (Section requires an actual source, Intel sources are not acceptable for debatable specifics.)[7]
December 2008: Intel changes the specification for their FMA instructions from 4-operand to 3-operand instructions. The VEX coding scheme is still used.[8]
May 2009: AMD changes the specification of their FMA instructions from the 3-operand DREX form to the 4-operand VEX form, compatible with the April 2008 Intel specification rather than the December 2008 Intel specification.[9]
October 2011: AMD Bulldozer processor supports FMA4.[10]
January 2012: AMD announces FMA3 support in future processors codenamed Trinity and Vishera; they are based on the Piledriver architecture.[11]
May 2012: AMD Piledriver processor supports both FMA3 and FMA4.[10]
June 2013: Intel Haswell processor supports FMA3.[12]
AMD explicitly revealed that Zen, its 3rd-generation x86-64 architecture in its first iteration (znver1 – Zen, version 1); would drop support for FMA4 in a patch to the GNU Binutils package.[13] There has been initial confusion regarding whether FMA4 was implemented or not due to errata in the initial patch that has since then been rectified.[14]

**Comment by aportelli** [comment]
Ok that's interesting!
